[package]
name = "k10-dependency-graph"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "10k-dependency-graph"
path = "src/main.rs"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34"
